### ISSUE TITLE
Unwanted meta tag

### ISSUE THREAD

**Issue by macx** [Gamesome-ab/astro-font#3]
The following meta tag is injected into my website. Could you please remove this?

https://github.com/Gamesome-ab/astro-font/blob/338d0aa6de4d81f00d5a6acfaf3ef892929ceefa/components/AstroFont.astro#L13

**Comment by jsve** [comment]
Nice catch! Of course! This has been removed in the new release we just pushed to NPM.

I'll close this issue. Please re-open if you disagree that the issue has been resolved!
